import { useEffect, useState } from "react";
import { NODE_BY_ID, type Node, type NodeBody, type NodeIndex } from "@/data/nodes";

/**
 * Loads the on-demand half of a node (layer1, layer2, quiz, furtherReading)
 * from `/content/bodies/<clusterId>.json`, one file per cluster, generated by
 * scripts/build-content.ts.
 *
 * Why per cluster and not per node: a reader who opens one idea in a topic
 * usually opens its neighbours next (related links are ~67% intra-cluster),
 * so one ~6 KB gz fetch covers the next several taps; and 38 files is a
 * precache list the service worker can hold, 387 is not worth it.
 *
 * Why a module-level cache and not TanStack Query: bodies are immutable for
 * a deploy (their content hash is in manifest.json and the SW cache key),
 * there is nothing to invalidate or refetch, and the node page must render
 * synchronously on a second visit. A Map does that with no provider.
 *
 * SSR: the server has the files on disk but we deliberately don't read them
 * there — the node page renders the index part (title, thesis, layer0) on
 * the server and streams the body in on the client, which keeps the HTML
 * small and identical between server and client (no hydration mismatch).
 */

type ClusterBodies = Record<string, NodeBody>;

const loaded = new Map<string, ClusterBodies>();
const inflight = new Map<string, Promise<ClusterBodies>>();

export function bodiesUrl(clusterId: string): string {
  return `/content/bodies/${clusterId}.json`;
}

export function loadClusterBodies(clusterId: string): Promise<ClusterBodies> {
  const hit = loaded.get(clusterId);
  if (hit) return Promise.resolve(hit);
  const pending = inflight.get(clusterId);
  if (pending) return pending;
  const p = fetch(bodiesUrl(clusterId), { credentials: "same-origin" })
    .then((r) => {
      if (!r.ok) throw new Error(`bodies ${clusterId}: HTTP ${r.status}`);
      return r.json() as Promise<ClusterBodies>;
    })
    .then((data) => {
      loaded.set(clusterId, data);
      inflight.delete(clusterId);
      return data;
    })
    .catch((e) => {
      inflight.delete(clusterId);
      throw e;
    });
  inflight.set(clusterId, p);
  return p;
}

/** Synchronous lookup — only if the cluster has already been loaded. */
export function getBody(node: NodeIndex): NodeBody | undefined {
  return loaded.get(node.clusterId)?.[node.id];
}

export function withBody(index: NodeIndex, body: NodeBody): Node {
  return { ...index, ...body };
}

/** Fire-and-forget warm of a cluster, e.g. on hover/preload of a node link. */
export function prefetchBodies(clusterId: string): void {
  void loadClusterBodies(clusterId).catch(() => {});
}

export type BodyState =
  | { status: "loading"; body: undefined; error: undefined }
  | { status: "ready"; body: NodeBody; error: undefined }
  | { status: "error"; body: undefined; error: Error };

/**
 * The node's body, loading it if needed. Returns synchronously-ready on a
 * second visit to any node in the same cluster. `error` is set when the
 * fetch fails (offline before the SW precache landed, or a bad deploy) so
 * the page can say so instead of hanging on a skeleton.
 */
export function useNodeBody(node: NodeIndex | undefined): BodyState {
  const cached = node ? getBody(node) : undefined;
  const [state, setState] = useState<BodyState>(
    cached
      ? { status: "ready", body: cached, error: undefined }
      : { status: "loading", body: undefined, error: undefined },
  );

  useEffect(() => {
    if (!node) return;
    let cancelled = false;
    const hit = getBody(node);
    if (hit) {
      setState({ status: "ready", body: hit, error: undefined });
      return;
    }
    setState({ status: "loading", body: undefined, error: undefined });
    loadClusterBodies(node.clusterId).then(
      (all) => {
        if (cancelled) return;
        const body = all[node.id];
        if (body) setState({ status: "ready", body, error: undefined });
        else
          setState({
            status: "error",
            body: undefined,
            error: new Error(`No body for ${node.id} in ${node.clusterId}`),
          });
      },
      (e: unknown) => {
        if (!cancelled)
          setState({
            status: "error",
            body: undefined,
            error: e instanceof Error ? e : new Error(String(e)),
          });
      },
    );
    return () => {
      cancelled = true;
    };
  }, [node]);

  return state;
}

/** Convenience for places that hold an id rather than an index entry. */
export function useNodeById(id: string | undefined): { index: NodeIndex | undefined } & BodyState {
  const index = id ? NODE_BY_ID[id] : undefined;
  const state = useNodeBody(index);
  return { index, ...state };
}

/** Test/SSR helper: seed the cache without a network. */
export function primeBodies(clusterId: string, bodies: ClusterBodies): void {
  loaded.set(clusterId, bodies);
}
