/**
 * build-content.ts — derive the app's data files from content/.
 *
 *   bun run scripts/build-content.ts            # write
 *   bun run scripts/build-content.ts --check    # exit 1 if outputs are stale
 *
 * Reads  content/clusters.json, content/tags.json, content/clusters/<id>.json
 * Writes src/data/nodes.ts                — INDEX: every node minus the body
 *                                            fields, plus CLUSTERS, TAGS and
 *                                            the derived maps. Bundled.
 *        public/content/bodies/<clusterId>.json — BODIES: layer1, layer2, quiz,
 *                                            furtherReading per node, fetched
 *                                            the first time a node in that
 *                                            cluster is opened; precached by
 *                                            the service worker.
 *        public/content/bodies/manifest.json    — { clusterId: contentHash }
 *                                            so the SW cache key changes
 *                                            exactly when a body changes.
 *
 * Deterministic: same content in → byte-identical files out, so CI can run
 * `--check` and fail a PR that edited content/ without rebuilding (or, worse,
 * hand-edited a generated file).
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import * as prettier from "prettier";
import { BODY_FIELDS, readAllContent, type FullNode } from "./lib/content";

const CHECK = process.argv.includes("--check");
const OUT_TS = path.join(process.cwd(), "src/data/nodes.ts");
const OUT_BODIES = path.join(process.cwd(), "public/content/bodies");

const { clusters, nodes, tags, files } = readAllContent();

type IndexNode = Omit<FullNode, (typeof BODY_FIELDS)[number]>;
function toIndex(n: FullNode): IndexNode {
  const out = { ...n } as Record<string, unknown>;
  for (const f of BODY_FIELDS) delete out[f];
  return out as IndexNode;
}

// ---- src/data/nodes.ts --------------------------------------------------------
const header = `// GENERATED by scripts/build-content.ts from content/clusters/*.json — do not edit.
// This is the INDEX: every field the feed, explore, search and review screens
// need, for every node, bundled with the app. The heavier per-node body
// (layer1, layer2, quiz, furtherReading) lives in public/content/bodies/<cluster>.json
// and is loaded by src/lib/bodies.ts the first time a node in that cluster is
// opened. See docs/CONTENT-LAYER.md.

export type EpistemicStatus = "Canonical" | "Contemporary" | "Speculative";

/** What every screen has for every node, always. */
export type NodeIndex = {
  id: string;
  clusterId: string;
  title: string;
  author: string;
  year: number;
  medium: string;
  category: string;
  thesis: string;
  layer0?: string;
  related: string[];
  tags: string[];
  epistemicStatus?: EpistemicStatus;
};

export type Quiz = { question: string; options: string[]; correctIndex: number; explanation?: string };

export type FurtherReading = {
  label: string;
  source: string;
  url: string;
  type?: string;
  archive?: {
    status: "full" | "excerpt" | "unavailable";
    path?: string;
    retrieved?: string;
  };
};

/** The on-demand part of a node. */
export type NodeBody = {
  layer1?: string;
  layer2?: string;
  quiz: Quiz;
  furtherReading: FurtherReading[];
};

/** A node with its body loaded — what the node page and the quiz work with. */
export type Node = NodeIndex & NodeBody;

export type Cluster = { id: string; title: string; subtitle: string; icon: string };
`;

const tagsTs = `export const TAGS = ${JSON.stringify(tags, null, 2)} as const;
export type Tag = (typeof TAGS)[number];
`;

const clustersTs = `export const CLUSTERS: Cluster[] = ${JSON.stringify(clusters, null, 2)};
`;

const nodesTs = `export const NODES: NodeIndex[] = ${JSON.stringify(nodes.map(toIndex), null, 2)};
`;

const footer = `
export const NODE_BY_ID: Record<string, NodeIndex> = Object.fromEntries(NODES.map((n) => [n.id, n]));

export const NODES_BY_CLUSTER: Record<string, NodeIndex[]> = Object.fromEntries(
  CLUSTERS.map((c) => [c.id, NODES.filter((n) => n.clusterId === c.id)]),
);

export const CLUSTER_BY_ID: Record<string, Cluster> = Object.fromEntries(CLUSTERS.map((c) => [c.id, c]));
`;

// Prettier-format so the generated file is stable under `bun run format` and
// lint's prettier rule — otherwise every regen would produce a lint error or a
// spurious re-format diff.
const prettierConfig = (await prettier.resolveConfig(OUT_TS)) ?? {};
const tsOut = await prettier.format([header, tagsTs, clustersTs, nodesTs, footer].join("\n"), {
  ...prettierConfig,
  filepath: OUT_TS,
});

// ---- public/content/bodies/<cluster>.json -------------------------------------
const bodyFiles = new Map<string, string>();
const manifest: Record<string, string> = {};
for (const f of files) {
  const bodies: Record<string, Partial<FullNode>> = {};
  for (const n of f.nodes) {
    const b: Record<string, unknown> = {};
    for (const k of BODY_FIELDS) if (n[k] !== undefined) b[k] = n[k];
    bodies[n.id] = b;
  }
  // Compact JSON — this is a network payload, not something anyone reads.
  const text = JSON.stringify(bodies);
  bodyFiles.set(f.cluster.id, text);
  manifest[f.cluster.id] = crypto.createHash("sha256").update(text).digest("hex").slice(0, 12);
}
const manifestText = JSON.stringify(manifest, null, 2) + "\n";

// ---- write or check ---------------------------------------------------------------
const planned: Array<[string, string]> = [
  [OUT_TS, tsOut],
  [path.join(OUT_BODIES, "manifest.json"), manifestText],
  ...[...bodyFiles].map(
    ([id, text]) => [path.join(OUT_BODIES, `${id}.json`), text] as [string, string],
  ),
];

if (CHECK) {
  const stale = planned.filter(
    ([p, text]) => !fs.existsSync(p) || fs.readFileSync(p, "utf8") !== text,
  );
  const extra = fs.existsSync(OUT_BODIES)
    ? fs
        .readdirSync(OUT_BODIES)
        .filter(
          (f) =>
            f.endsWith(".json") &&
            f !== "manifest.json" &&
            !bodyFiles.has(f.replace(/\.json$/, "")),
        )
        .map((f) => path.join(OUT_BODIES, f))
    : [];
  if (stale.length || extra.length) {
    console.error(
      "Generated content is out of date. Run `bun run build:content` and commit the result.",
    );
    for (const [p] of stale) console.error(`  stale: ${path.relative(process.cwd(), p)}`);
    for (const p of extra) console.error(`  orphan: ${path.relative(process.cwd(), p)}`);
    process.exit(1);
  }
  console.log(
    `Generated content is up to date (${nodes.length} nodes, ${clusters.length} clusters).`,
  );
} else {
  fs.mkdirSync(OUT_BODIES, { recursive: true });
  for (const f of fs.readdirSync(OUT_BODIES)) {
    if (f.endsWith(".json") && f !== "manifest.json" && !bodyFiles.has(f.replace(/\.json$/, "")))
      fs.unlinkSync(path.join(OUT_BODIES, f));
  }
  for (const [p, text] of planned) fs.writeFileSync(p, text);
  const idxKb = Math.round(Buffer.byteLength(tsOut) / 1024);
  const bodyKb = Math.round(
    [...bodyFiles.values()].reduce((s, t) => s + Buffer.byteLength(t), 0) / 1024,
  );
  console.log(
    `Wrote src/data/nodes.ts (${nodes.length} nodes, ${idxKb} KB) and ${bodyFiles.size} body files (${bodyKb} KB) + manifest.`,
  );
}
