import { Project, SyntaxKind } from "ts-morph";

const project = new Project({ tsConfigFilePath: "tsconfig.json" });
const sourceFile = project.getSourceFileOrThrow("src/data/nodes.ts");

const nodesArray = sourceFile
  .getVariableDeclarationOrThrow("NODES")
  .getInitializerIfKindOrThrow(SyntaxKind.ArrayLiteralExpression);

const newNodes = [
  // AEON
  {
    id: "AA13",
    clusterId: "O", // Philosophy & the Self
    title: "Panpsychism",
    author: "Philip Goff",
    year: 2019,
    medium: "Philosophy",
    category: "Metaphysics",
    thesis:
      "Consciousness is not an illusion generated by complex brains; it is a fundamental property of all physical matter in the universe.",
    layer0:
      "Science can explain the physical mechanics of the brain, but it cannot explain why those mechanics are accompanied by the subjective feeling of being alive (the 'Hard Problem'). Panpsychism argues that we can't explain it because we have the equation backward.",
    layer1:
      "Instead of assuming that dead, unconscious matter somehow magically generates consciousness when arranged in a complex enough structure (like a human brain), panpsychism proposes that consciousness is a fundamental feature of the universe, just like mass, charge, and spin.",
    layer2:
      "Under this view, an electron doesn't sit around thinking about philosophy, but it has some unimaginably basic, rudimentary subjective experience. When elementary particles combine in highly complex ways (like in a biological brain), those micro-consciousnesses combine to form the rich macro-consciousness we experience as humans. It neatly solves the Hard Problem by removing the magic.",
    quiz: {
      question: "How does Panpsychism solve the 'Hard Problem' of consciousness?",
      options: [
        "By proving that consciousness is merely an illusion generated by software.",
        "By suggesting that consciousness is a fundamental property of matter, meaning it doesn't need to 'magically' emerge from dead atoms.",
        "By showing that only organisms with complex nervous systems can process information.",
        "By relying on quantum mechanics to explain free will.",
      ],
      correctIndex: 1,
      explanation:
        "If consciousness is already a basic property of the universe (like mass), you no longer have to explain how dead matter magically produces subjective experience.",
    },
    related: ["R1", "O6"], // The Hard Problem
    furtherReading: [
      {
        label: "Panpsychism",
        source: "Aeon",
        url: "https://aeon.co/essays/panpsychism-is-crazy-but-its-also-most-probably-true",
      },
    ],
    tags: ["Philosophy & the Self", "Meaning & Self"],
  },
  {
    id: "AA14",
    clusterId: "V", // Social Constructs
    title: "Epistemic Injustice",
    author: "Miranda Fricker",
    year: 2007,
    medium: "Philosophy",
    category: "Sociology",
    thesis:
      "When we dismiss someone's testimony or ability to know something simply because of their race, gender, or social class, we commit a unique kind of violence against them.",
    layer0:
      "Epistemic injustice occurs when a person is wronged specifically in their capacity as a 'knower.' It is the subtle, often unconscious bias that causes us to immediately doubt the credibility of certain groups of people.",
    layer1:
      "There are two main types. 'Testimonial injustice' is when a jury doesn't believe a witness because of his race, or a doctor ignores a woman's pain because he assumes she is being 'hysterical.' The person is speaking the truth, but prejudice deflates their credibility.",
    layer2:
      "'Hermeneutical injustice' is even deeper: it happens when a society lacks the very concepts or vocabulary needed for a marginalized group to explain their experience. Before the term 'sexual harassment' was coined in the 1970s, women who experienced it literally lacked the words to explain the systemic nature of their trauma to authorities.",
    quiz: {
      question: "What is an example of 'Testimonial Injustice'?",
      options: [
        "Refusing to hire someone because of their background.",
        "Failing to understand a complex philosophical argument.",
        "Dismissing a patient's description of their physical pain because of unconscious gender bias.",
        "Lacking the vocabulary to describe a new sociological phenomenon.",
      ],
      correctIndex: 2,
      explanation:
        "Testimonial injustice occurs when a person's testimony or credibility is unfairly deflated due to prejudice against their identity.",
    },
    related: ["V4", "V5"], // Social constructs
    furtherReading: [
      {
        label: "Epistemic Injustice",
        source: "Aeon",
        url: "https://aeon.co/essays/how-epistemic-injustice-harms-the-marginalised",
      },
    ],
    tags: ["Cognitive Biases & Models", "Social Constructs"],
  },
  {
    id: "AA15",
    clusterId: "Y", // Perception
    title: "Predictive Processing",
    author: "Andy Clark",
    year: 2013,
    medium: "Neuroscience",
    category: "Cognition",
    thesis:
      "Your brain does not passively receive reality through your eyes and ears. It hallucinates reality, and only uses your senses to correct its errors.",
    layer0:
      "We assume our eyes work like cameras, streaming data to the brain for processing. Neuroscience now suggests the opposite: the brain is locked in a dark, silent skull. It generates its own 'best guess' (a hallucination) of what is happening outside.",
    layer1:
      "This is called Predictive Processing. The brain sends its predictions down to the sensory organs. The sensory organs only send signals back up to the brain if reality *disagrees* with the prediction (prediction errors).",
    layer2:
      "When you walk down your familiar street, you aren't really 'seeing' it. Your brain is hallucinating it perfectly because it has prior data. You only truly 'see' something when a novel object (like a fallen tree) creates a prediction error, forcing the brain to update its internal model. You are literally hallucinating your reality right now, guided by sensory constraints.",
    quiz: {
      question:
        "According to Predictive Processing, what is the primary role of your sensory organs?",
      options: [
        "To stream high-definition reality into the brain for processing.",
        "To generate the hallucinations that form consciousness.",
        "To send signals to the brain only when reality differs from the brain's prediction.",
        "To permanently store long-term memories.",
      ],
      correctIndex: 2,
      explanation:
        "Sensory input is largely just an 'error-correction' mechanism. The brain does the heavy lifting of generating the world; the eyes and ears just report back when the brain's guess is wrong.",
    },
    related: ["O1", "Y1"], // Reality & Perception
    furtherReading: [
      {
        label: "The Predictive Brain",
        source: "Aeon",
        url: "https://aeon.co/essays/how-the-predictive-brain-makes-us-hallucinate-our-reality",
      },
    ],
    tags: ["Philosophy & the Self", "Cognitive Biases & Models"],
  },

  // LESSWRONG
  {
    id: "AA16",
    clusterId: "J", // Mental Models
    title: "The Map is Not the Territory",
    author: "Alfred Korzybski",
    year: 1931,
    medium: "Mental Model",
    category: "Epistemology",
    thesis:
      "Our mental models of reality are reductions. When the model contradicts reality, the model is wrong, not reality.",
    layer0:
      "A map of Paris is not Paris. If the map perfectly replicated Paris down to every single atom, it would be the size of Paris and therefore useless. All models, by definition, must leave out details to be useful.",
    layer1:
      "We navigate life using 'maps'—economic theories, political ideologies, stereotypes, and mathematical formulas. The danger occurs when we mistake the map for the territory. When a spreadsheet says a business decision makes sense, but the actual human customers hate it, the spreadsheet (the map) is wrong.",
    layer2:
      "The map is not the territory, the menu is not the meal, and the word is not the thing. High-level thinkers constantly update their maps based on contact with the territory. Ideologues do the opposite: when the territory behaves unpredictably, they blame the territory for failing to conform to their beautiful, perfect map.",
    quiz: {
      question: "What is the primary danger described by 'The Map is Not the Territory'?",
      options: [
        "Maps are often drawn with incorrect geographical coordinates.",
        "We forget that our mental models are reductive tools and mistake them for absolute reality.",
        "It proves that all science and mathematics are fundamentally useless.",
        "We spend too much time navigating and not enough time acting.",
      ],
      correctIndex: 1,
      explanation:
        "A model is a simplified tool. When we forget it's a simplification and treat it as absolute truth, we make catastrophic errors when encountering complex reality.",
    },
    related: ["J1", "U1"], // All Models Are Wrong
    furtherReading: [
      {
        label: "The Map is Not the Territory",
        source: "LessWrong",
        url: "https://www.lesswrong.com/tag/the-map-is-not-the-territory",
      },
    ],
    tags: ["Cognitive Biases & Models", "Decision-Making"],
  },
  {
    id: "AA17",
    clusterId: "U", // Cognitive Biases
    title: "Steelmanning",
    author: "Eliezer Yudkowsky",
    year: 2007,
    medium: "Concept",
    category: "Rationality",
    thesis:
      "To truly win an argument or seek truth, you must first construct the absolute strongest, most bulletproof version of your opponent's view before refuting it.",
    layer0:
      "A 'strawman' argument is when you intentionally misrepresent your opponent's position, making it sound stupid so it's easy to knock down. 'Steelmanning' is the exact opposite.",
    layer1:
      "When you steelman, you help your opponent build the strongest possible version of their argument. You fix their logical flaws, supply them with better data, and articulate their position so well that they say, 'Yes, I wish I had said it exactly like that.'",
    layer2:
      "Only after you have steelmanned the argument are you allowed to attack it. If you can dismantle the steelman, you have actually proven your point and advanced the truth. If you only attack strawmen, you are just performing ego-driven theater and tricking yourself into thinking you are right.",
    quiz: {
      question: "Why is 'Steelmanning' considered superior to attacking a weak argument?",
      options: [
        "It humiliates the opponent by showing you are smarter than them.",
        "It is the only way to genuinely test if your own beliefs can survive contact with the strongest opposing evidence.",
        "It forces the opponent to concede faster out of exhaustion.",
        "It requires less cognitive effort than building a strawman.",
      ],
      correctIndex: 1,
      explanation:
        "Truth-seeking requires testing your beliefs against the strongest possible counter-arguments, not the weakest ones.",
    },
    related: ["U2", "L2"], // Rationality
    furtherReading: [
      {
        label: "Steelmanning",
        source: "LessWrong",
        url: "https://www.lesswrong.com/tag/steelmanning",
      },
    ],
    tags: ["Cognitive Biases & Models", "First-Principles Thinking"],
  },
  {
    id: "AA18",
    clusterId: "U", // Cognitive Biases
    title: "Motivated Stopping",
    author: "Eliezer Yudkowsky",
    year: 2007,
    medium: "Concept",
    category: "Cognitive Bias",
    thesis:
      "When you want to believe something, you stop looking for evidence at the first confirming fact. When you don't want to believe it, you demand impossible proof.",
    layer0:
      "Humans are not impartial truth-seekers; we are lawyers arguing for a predetermined verdict. This manifests in two behaviors: Motivated Stopping and Motivated Continuation.",
    layer1:
      "If you want to buy a shiny new car you can't afford, you will Google 'is the new car reliable?' You find one positive review, experience 'Motivated Stopping,' and close the browser feeling justified.",
    layer2:
      "Conversely, if someone presents you with irrefutable evidence that your political party made a mistake, you experience 'Motivated Continuation.' You will endlessly demand more sources, question the methodology of the studies, and keep the search going until you find one obscure blog post that lets you dismiss the evidence entirely.",
    quiz: {
      question: "What triggers 'Motivated Stopping' in human psychology?",
      options: [
        "A lack of available information on the internet.",
        "Finding the very first piece of evidence that supports a belief you already want to hold.",
        "Physical exhaustion from reading too many academic papers.",
        "The realization that the opposing argument has been steelmanned.",
      ],
      correctIndex: 1,
      explanation:
        "Our brains are lazy and biased. As soon as we find a single excuse to believe what we already want to believe, we stop the search.",
    },
    related: ["U3", "U4"], // Confirmation Bias
    furtherReading: [
      {
        label: "Motivated Stopping",
        source: "LessWrong",
        url: "https://www.lesswrong.com/tag/motivated-stopping-and-motivated-continuation",
      },
    ],
    tags: ["Cognitive Biases & Models", "Decision-Making"],
  },
];

newNodes.forEach((node) => {
  nodesArray.addElement(JSON.stringify(node, null, 2));
});

sourceFile.saveSync();
console.log(`Successfully injected ${newNodes.length} nodes from Batch 3.`);
